In [1]:
import numpy as np #importing numpy for use
import pandas as pd #pandas make sorting in dataframes easier 

In [2]:
big_array = np.random.randint(1, 501, size=100) #Creating a 500 number array
big_array

array([143,  91, 361, 250, 126, 320, 304, 138, 129, 189, 192, 179, 107,
       149, 223, 157, 434, 461, 410, 185, 190, 393, 353, 264, 439, 132,
       221, 249, 102, 443, 292, 230, 348,  65, 111, 358, 135, 257,  67,
       453, 255,  25, 216, 222, 113, 253,  45, 457, 244, 479, 332, 230,
       114,  49,  60, 252, 197, 385,  36, 314,  64,  79, 328,  31, 119,
       229, 341, 202,   6, 350, 447, 491,  13,  16,  69, 152, 348, 360,
       393,  63, 116, 329, 104, 378, 448,  54, 143, 467, 327,   9, 466,
       219, 158,  40,  72, 345, 342,  73, 435, 284], dtype=int32)

In [3]:
big_matrix = big_array.reshape(10, 10) #reshaping array into a 10x10 matrix
big_matrix

array([[143,  91, 361, 250, 126, 320, 304, 138, 129, 189],
       [192, 179, 107, 149, 223, 157, 434, 461, 410, 185],
       [190, 393, 353, 264, 439, 132, 221, 249, 102, 443],
       [292, 230, 348,  65, 111, 358, 135, 257,  67, 453],
       [255,  25, 216, 222, 113, 253,  45, 457, 244, 479],
       [332, 230, 114,  49,  60, 252, 197, 385,  36, 314],
       [ 64,  79, 328,  31, 119, 229, 341, 202,   6, 350],
       [447, 491,  13,  16,  69, 152, 348, 360, 393,  63],
       [116, 329, 104, 378, 448,  54, 143, 467, 327,   9],
       [466, 219, 158,  40,  72, 345, 342,  73, 435, 284]], dtype=int32)

In [4]:
big_matrix[:, 2] #accessing the 3 column and printing it out

array([361, 107, 353, 348, 216, 114, 328,  13, 104, 158], dtype=int32)

In [5]:
tiny_matrix = big_matrix[1:5, 3:8] #creating a smaller matrix of rows 2 to 5 and columns 4 to 8
tiny_matrix

array([[149, 223, 157, 434, 461],
       [264, 439, 132, 221, 249],
       [ 65, 111, 358, 135, 257],
       [222, 113, 253,  45, 457]], dtype=int32)

In [6]:
def big_matrix_over_200(): #creating a function to return all values over 200 in matrix
    large_valuematrix = big_matrix[big_matrix>200]
    print(large_valuematrix)
    return
big_matrix_over_200() 

[361 250 320 304 223 434 461 410 393 353 264 439 221 249 443 292 230 348
 358 257 453 255 216 222 253 457 244 479 332 230 252 385 314 328 229 341
 202 350 447 491 348 360 393 329 378 448 467 327 466 219 345 342 435 284]


In [7]:
def big_matrix_under_100(): # Replace all elements less than 100 with 0
    big_matrix[big_matrix < 100] = 0
    return

big_matrix

array([[143,  91, 361, 250, 126, 320, 304, 138, 129, 189],
       [192, 179, 107, 149, 223, 157, 434, 461, 410, 185],
       [190, 393, 353, 264, 439, 132, 221, 249, 102, 443],
       [292, 230, 348,  65, 111, 358, 135, 257,  67, 453],
       [255,  25, 216, 222, 113, 253,  45, 457, 244, 479],
       [332, 230, 114,  49,  60, 252, 197, 385,  36, 314],
       [ 64,  79, 328,  31, 119, 229, 341, 202,   6, 350],
       [447, 491,  13,  16,  69, 152, 348, 360, 393,  63],
       [116, 329, 104, 378, 448,  54, 143, 467, 327,   9],
       [466, 219, 158,  40,  72, 345, 342,  73, 435, 284]], dtype=int32)

In [8]:
#BASIC STATS CALCULATIONS (I may need to make this more legible)
std = np.std(big_matrix)
var = np.var(big_matrix)
mean = np.mean(big_matrix)
med = np.median(big_matrix)

print(f"Standard Deviation: {std}")
print(f"Mean: {mean}")
print(f"Median: {med}")
print(f"Variance: {var}")

Standard Deviation: 138.75487595036074
Mean: 228.38
Median: 221.5
Variance: 19252.915599999997


In [9]:
#Mean of each row and column 
row_means = np.mean(big_matrix, axis=1)
column_means = np.mean(big_matrix, axis=0)
print(f"Row Means: {row_means}")
print(f"Column Means: {column_means}")

Row Means: [205.1 249.7 278.6 231.6 230.9 196.9 174.9 235.2 237.5 243.4]
Column Means: [249.7 226.6 210.2 146.4 178.  225.2 251.  304.9 214.9 276.9]


In [10]:
#Sorting each row of matrix in ascending order 
sorted_rows_ascend = np.sort(big_matrix, axis=1) 
sorted_rows_ascend


array([[ 91, 126, 129, 138, 143, 189, 250, 304, 320, 361],
       [107, 149, 157, 179, 185, 192, 223, 410, 434, 461],
       [102, 132, 190, 221, 249, 264, 353, 393, 439, 443],
       [ 65,  67, 111, 135, 230, 257, 292, 348, 358, 453],
       [ 25,  45, 113, 216, 222, 244, 253, 255, 457, 479],
       [ 36,  49,  60, 114, 197, 230, 252, 314, 332, 385],
       [  6,  31,  64,  79, 119, 202, 229, 328, 341, 350],
       [ 13,  16,  63,  69, 152, 348, 360, 393, 447, 491],
       [  9,  54, 104, 116, 143, 327, 329, 378, 448, 467],
       [ 40,  72,  73, 158, 219, 284, 342, 345, 435, 466]], dtype=int32)

In [11]:
sorted_by_2ndcol = big_matrix[big_matrix[:, 1].argsort()]
sorted_by_2ndcol

array([[255,  25, 216, 222, 113, 253,  45, 457, 244, 479],
       [ 64,  79, 328,  31, 119, 229, 341, 202,   6, 350],
       [143,  91, 361, 250, 126, 320, 304, 138, 129, 189],
       [192, 179, 107, 149, 223, 157, 434, 461, 410, 185],
       [466, 219, 158,  40,  72, 345, 342,  73, 435, 284],
       [332, 230, 114,  49,  60, 252, 197, 385,  36, 314],
       [292, 230, 348,  65, 111, 358, 135, 257,  67, 453],
       [116, 329, 104, 378, 448,  54, 143, 467, 327,   9],
       [190, 393, 353, 264, 439, 132, 221, 249, 102, 443],
       [447, 491,  13,  16,  69, 152, 348, 360, 393,  63]], dtype=int32)

In [12]:
#MOVING TO PART 2
sales_data = np.array([[200, 250, 300, 150],  # Jan
                       [180, 220, 280, 140],  # Feb
                       [220, 270, 310, 170],  # Mar
                       [210, 260, 330, 160],  # Apr
                       [230, 280, 320, 180],  # May
                       [190, 240, 300, 150],  # Jun
                       [210, 260, 310, 160],  # Jul
                       [250, 290, 340, 190],  # Aug
                       [220, 270, 310, 170],  # Sep
                       [230, 280, 320, 180],  # Oct
                       [240, 290, 330, 190],  # Nov
                       [260, 300, 340, 200]]) # Dec
                                    

In [13]:
#Finding total sales for each product over year
total_sales_p1 = np.sum(sales_data[:, 0])
total_sales_p2 = np.sum(sales_data[:, 1])
total_sales_p3 = np.sum(sales_data[:, 2])
total_sales_p4 = np.sum(sales_data[:, 3])

print(f"p1 Sales: {total_sales_p1}")
print(f"p2 Sales: {total_sales_p2}")
print(f"p3 Sales: {total_sales_p3}")
print(f"p4 Sales: {total_sales_p4}")

p1 Sales: 2640
p2 Sales: 3210
p3 Sales: 3790
p4 Sales: 2040


In [14]:
#Adding Products and row titles for Clarity, switching to pandas based calculations for ease here
sales_data2 = pd.DataFrame(sales_data, columns = ['P1', 'P2', 'P3', 'P4'], index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']) 
sales_data2

P1   P2   P3   P4
Jan  200  250  300  150
Feb  180  220  280  140
Mar  220  270  310  170
Apr  210  260  330  160
May  230  280  320  180
Jun  190  240  300  150
Jul  210  260  310  160
Aug  250  290  340  190
Sep  220  270  310  170
Oct  230  280  320  180
Nov  240  290  330  190
Dec  260  300  340  200

In [15]:
#Month with highest sales for each product 
max_sales_p1 = sales_data2['P1'].max()
max_sales_p2 = sales_data2['P2'].max()
max_sales_p3 = sales_data2['P2'].max()
max_sales_p4 = sales_data2['P2'].max()

print("Maximum sales for P1:", max_sales_p1)
print("Maximum sales for P2:", max_sales_p2)
print("Maximum sales for P3:", max_sales_p3)
print("Maximum sales for P4:", max_sales_p4)

Maximum sales for P1: 260
Maximum sales for P2: 300
Maximum sales for P3: 300
Maximum sales for P4: 300


In [16]:
#Average sales per month for all products -- wasted time here created a more efficient function below
avg_Jan_sales = sales_data2.loc['Jan'].mean()
avg_Feb_sales = sales_data2.loc['Feb'].mean()
avg_Mar_sales = sales_data2.loc['Mar'].mean()
avg_Apr_sales = sales_data2.loc['Apr'].mean()
avg_May_sales = sales_data2.loc['May'].mean()
avg_Jun_sales = sales_data2.loc['Jun'].mean()
avg_Jul_sales = sales_data2.loc['Jul'].mean()
avg_Aug_sales = sales_data2.loc['Aug'].mean()
avg_Sep_sales = sales_data2.loc['Sep'].mean()
avg_Oct_sales = sales_data2.loc['Oct'].mean()
avg_Nov_sales = sales_data2.loc['Nov'].mean()
avg_Dec_sales = sales_data2.loc['Dec'].mean()

print("Avg Jan sales:", avg_Jan_sales)
print("Avg Feb sales:", avg_Feb_sales)
print("Avg Mar sales:", avg_Mar_sales)
print("Avg Apr sales:", avg_Apr_sales)
print("Avg May sales:", avg_May_sales)
print("Avg Jun sales:", avg_Jun_sales)
print("Avg Jul sales:", avg_Jul_sales)
print("Avg Aug sales:", avg_Aug_sales)
print("Avg Sep sales:", avg_Sep_sales)
print("Avg Oct sales:", avg_Oct_sales)
print("Avg Nov sales:", avg_Nov_sales)
print("Avg Dec sales:", avg_Dec_sales)

Avg Jan sales: 225.0
Avg Feb sales: 205.0
Avg Mar sales: 242.5
Avg Apr sales: 240.0
Avg May sales: 252.5
Avg Jun sales: 220.0
Avg Jul sales: 235.0
Avg Aug sales: 267.5
Avg Sep sales: 242.5
Avg Oct sales: 252.5
Avg Nov sales: 262.5
Avg Dec sales: 275.0


In [17]:
#Average sales per month MORE EFFICIENT 
avg_sales_per_month = sales_data2.mean(axis=1)

print("Average sales per month:\n", avg_sales_per_month)

Average sales per month:
 Jan    225.0
Feb    205.0
Mar    242.5
Apr    240.0
May    252.5
Jun    220.0
Jul    235.0
Aug    267.5
Sep    242.5
Oct    252.5
Nov    262.5
Dec    275.0
dtype: float64


In [18]:
#Finding month with highest average sales 
max_avg_sales = avg_sales_per_month.max()  # Maximum value
max_avg_sales_month = avg_sales_per_month.idxmax()  # Month corresponding to the maximum

print(f"The month with the highest average sales is {max_avg_sales_month}, with an average sales value of {max_avg_sales}.")

The month with the highest average sales is Dec, with an average sales value of 275.0.


In [19]:
#MOVING INTO CUSTOMER SEGMENTATION 
basic_customers = np.random.randint(50, 251, size=50)
silver_customers = np.random.randint(100, 351, size=50)
gold_customers = np.random.randint(200, 551, size=50)

# Converting into pandas DataFrames and storing them in variables
df_basic_customers = pd.DataFrame(basic_customers, columns=['Basic Customers'])
df_silver_customers = pd.DataFrame(silver_customers, columns=['Silver Customers'])
df_gold_customers = pd.DataFrame(gold_customers, columns=['Gold Customers'])

print(df_basic_customers.head())
print(df_silver_customers.head())
print(df_gold_customers.head())

   Basic Customers
0              233
1              122
2              170
3              152
4              203
   Silver Customers
0               261
1               321
2               260
3               196
4               106
   Gold Customers
0             371
1             531
2             527
3             452
4             441


In [20]:
#average spending customers
basic_spending = df_basic_customers['Basic Customers'].mean()
silver_spending = df_silver_customers['Silver Customers'].mean()
gold_spending = df_gold_customers['Gold Customers'].mean()

print(f"Average spending for basic customers: {basic_spending:.2f}")
print(f"Average spending for silver customers: {silver_spending:.2f}")
print(f"Average spending for gold customers: {gold_spending:.2f}")

Average spending for basic customers: 145.54
Average spending for silver customers: 237.44
Average spending for gold customers: 390.06


In [21]:
#percentage of customers who spend more than $250

basic_250_count = (df_basic_customers['Basic Customers'] > 250).sum()
silver_250_count = (df_silver_customers['Silver Customers'] > 250).sum()
gold_250_count = (df_gold_customers['Gold Customers'] > 250).sum()

basic_250_perc= (basic_250_count / len(df_basic_customers)) * 100
silver_250_perc= (silver_250_count / len(df_silver_customers)) * 100
gold_250_perc= (gold_250_count / len(df_gold_customers)) * 100 #calculating percentage 

print(f"Percentage of basic customers who spend more than $250: {basic_250_perc:.2f}%")
print(f"Percentage of silver customers who spend more than $250: {silver_250_perc:.2f}%")
print(f"Percentage of gold customers who spend more than $250: {gold_250_perc:.2f}%")


Percentage of basic customers who spend more than $250: 0.00%
Percentage of silver customers who spend more than $250: 52.00%
Percentage of gold customers who spend more than $250: 96.00%


In [22]:
#Creating an Array with all three 
#Concatenate the DataFrames side by side (along columns)
df_all = pd.concat([df_basic_customers, df_silver_customers, df_gold_customers], axis=1)

#Rename the columns for clarity
df_all.columns = ['Basic Customers', 'Silver Customers', 'Gold Customers']
print(df_all)


    Basic Customers  Silver Customers  Gold Customers
0               233               261             371
1               122               321             531
2               170               260             527
3               152               196             452
4               203               106             441
5                56               114             462
6                85               328             507
7               172               111             495
8               176               132             441
9                52               150             299
10              222               218             351
11              176               341             325
12              224               100             461
13              165               310             356
14               86               240             314
15               75               329             480
16              247               128             458
17              185         

In [23]:
# Calculate the overall mean and standard deviation (flattening all values into one series)
mean_spend = df_all.mean().mean()  # Mean of each column and then mean of that value
stddev_spend = df_all.stack().std()  # Standard deviation across all values

print(f"The average spending across all customer types was $ {mean_spend:.2f}")
print(f"The standard deviation of spending across all customer types was $ {stddev_spend:.2f}")


The average spending across all customer types was $ 257.68
The standard deviation of spending across all customer types was $ 129.08


In [24]:
#MATRIX Operations
A = np.random.randint(1,51, size=9) 
B = np.random.randint(1,51, size=9)

A_mat = pd.DataFrame(A.reshape(3, 3)) #converting to pandas for matrices 
B_mat = pd.DataFrame(B.reshape(3, 3))

In [25]:
#calculating product of A and B **element wise 

productAB = A_mat * B_mat

In [26]:
#matrix multiplication of A and B
matrix_multiplication = np.dot(A_mat, B_mat)

print("Matrix A:")
print(A_mat)

print("\nMatrix B:")
print(B_mat)

print("\nElement-wise product of A and B:")
print(pd.DataFrame(productAB))

print("\nMatrix multiplication (dot product) of A and B:")
print(pd.DataFrame(matrix_multiplication))

Matrix A:
    0   1   2
0  17  28  24
1  33  17   8
2   5  10  24

Matrix B:
    0   1   2
0  10  31   4
1  23   1  18
2  39  16  40

Element-wise product of A and B:
     0    1    2
0  170  868   96
1  759   17  144
2  195  160  960

Matrix multiplication (dot product) of A and B:
      0     1     2
0  1750   939  1532
1  1033  1168   758
2  1216   549  1160


In [27]:
# Create a 2x2 matrix
matrix_2x2 = np.array([[3, 8],
                       [1, 4]])

#Find the determinant
determinant = np.linalg.det(matrix_2x2)

#Calculate the inverse
if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix_2x2)
else:
    inverse_matrix = None

#Verify matrix multiplied by inverse gives the identity matrix
if inverse_matrix is not None:
    identity_matrix = np.dot(matrix_2x2, inverse_matrix)
else:
    identity_matrix = None

print("Original 2x2 Matrix:")
print(matrix_2x2)

print("\nDeterminant of the matrix:", determinant)

if inverse_matrix is not None:
    print("\nInverse of the matrix:")
    print(inverse_matrix)

    print("\nMatrix multiplied by its inverse (should be the identity matrix):")
    print(identity_matrix)
else:
    print("\nThe matrix does not have an inverse (determinant is zero).")


Original 2x2 Matrix:
[[3 8]
 [1 4]]

Determinant of the matrix: 4.000000000000001

Inverse of the matrix:
[[ 1.   -2.  ]
 [-0.25  0.75]]

Matrix multiplied by its inverse (should be the identity matrix):
[[1.0000000e+00 8.8817842e-16]
 [0.0000000e+00 1.0000000e+00]]


In [28]:
#Linear Regression Analyis method with equation y = mx + b
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
y = np.array([25, 45, 65, 80, 100, 130, 150, 180, 210, 240])

# Number of data points
n = len(x)

# Calculating the sums needed for the formulas
sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x2 = np.sum(x ** 2)

# Calculating the slope (m) and intercept (b)
m = (n * sum_xy - sum_x * sum_y) / (n * sum_x2 - sum_x ** 2) #using slope formula from lab handout 
b = (sum_y * sum_x2 - sum_x * sum_xy) / (n * sum_x2 - sum_x ** 2) #intercept formula

# Displaying the results
print(f"Slope (m): {m}")
print(f"Intercept (b): {b}")

# Using the slope and intercept to calculate the predicted y values (y = mx + b)
y_pred = m * x + b

# Display the best-fit line equation
print(f"The equation of the best-fit line is: y = {m:.2f}x + {b:.2f}")

Slope (m): 2.3666666666666667
Intercept (b): -7.666666666666667
The equation of the best-fit line is: y = 2.37x + -7.67


In [29]:
#Calculating for 120 using m and c 
advertising = 120

sales_predict = m * advertising + b 

print(f"Predicted sales for an advertising budget of {advertising}: {sales_predict:.2f}")

Predicted sales for an advertising budget of 120: 276.33


In [30]:
#Calculate the mean squared error (MSE) of the regression model.
mse = np.mean((y - y_pred) ** 2)

# Print the result
print(f"Mean Squared Error (MSE) of the regression model: {mse:.4f}")

Mean Squared Error (MSE) of the regression model: 50.3333
